#!/bin/sh
LINKDIR=$(readlink $0)
BASEDIR=$0

if [ "$BASEDIR" != "" ]
then
	BASEDIR=$(dirname $BASEDIR)
fi

if [ "$LINKDIR" != "" ]
then
	BASEDIR=$BASEDIR/$(dirname $LINKDIR)
fi

`which node` $BASEDIR/crafity.js $1 $2 $3 $4 $5 $6 $7 $8 $9
